version: '3.8'

services:
  db:
    build: ./postgres-docker
    container_name: my-postgres-container
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"

  web:
    build: ./nextjs-docker-app
    container_name: next-app-container
    ports:
      - "3000:3000"